version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - bumpp
  - destr
  - masknet
  - moeru
  - ofetch
  - oofetch
  - ooofetch
  - pkgroll
  - sonarjs
  - unjs
ignoreWords: []
import: []
